name: build
on: [push, pull_request]

# name: build
# on:
#   push:
#     # Action run will only be triggered on updates to master branch
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install

      - name: Build
        run: |
          ./scripts/build
        env:
          VIMEO_API_TOKEN: ${{ secrets.VIMEO_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
